server:
  port: 8082
  servlet:
    context-path: /
dubbo:
  application:
    name: shop_name
    qos-enable: true
    qos-accept-foreign-ip: false
    qos-port: 44444
  scan:
    base-packages: com.shop.controller
  registry:
    address: zookeeper://192.168.25.142:2181
  consumer:
    timeout: 10000
    check: true
    retries: 2
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop?useUnicode=true&characterEncoding=utf8&autoReconnect=true&testOnBorrow=true&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  #thymeleaf
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    servlet:
      content-type: text/html
    enabled: true
    encoding: UTF-8
    mode: HTML5
mybatis:
  mapper-locations: classpath:mapper/*.xml    #配置映射文件
  type-aliases-package: com.shop.pojo   #配置实体类
pagehelper:
  helperDialect: mysql
  reasonable: true #开启优化，<1页返回第一页
  supportMethodsArguments: true #是否支持接口参数来传递分页参数，默认false
  pageSizeZero: false #pageSize=0 返回所有
  params: count=countSql
